### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by kylejb** [clairBuoyant/web#9]
## What

Create components for Navbar as per initial [design](https://www.figma.com/file/w6U76lUUe69fodXwsMKBjK/Web-(desktop)?node-id=0%3A1). Disregard user authentication for now.

**Comment by Mleng89** [comment]
@Grieze Let me know if you anticipate any drastic changes in the design.

**Comment by Grieze** [comment]
@Mleng89 Sounds good to me, will let you know.
